Class ODS.Procedure Extends ODS.DT.AbstractResource
{




Storage Default
{
<Data name="ProcedureDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>ResourceId</Value>
</Value>
</Data>
<DataLocation>^ODS.ProcedureD</DataLocation>
<DefaultData>ProcedureDefaultData</DefaultData>
<IdLocation>^ODS.ProcedureD</IdLocation>
<IndexLocation>^ODS.ProcedureI</IndexLocation>
<StreamLocation>^ODS.ProcedureS</StreamLocation>
<Type>%Library.CacheStorage</Type>
}

}